language: python
python:
- '2.7'
install: pip install -r requirements/dev.txt
cache: pip
env:
- CONFIG='beacon.settings.TestConfig'
before_script:
- psql -c 'create database beacon_test;' -U postgres
script: PYTHONPATH=. nosetests test/ --with-coverage --cover-package=purchasing
addons:
  postgresql: "9.4"
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
